ONECOND-2262-Create API for cancelling workflows based on JobId
d3sw/conductor pull request #985
Opened 2023-08-16 07:53 UTC by sangeetanadgir

2023-08-16 22:15 UTC, pradeeppalat01 requested changes

2023-08-17 06:55 UTC, sangeetanadgir commented on jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
> +                    if (!bypassAuth(headers)) {
fixed it

2023-08-17 06:57 UTC, sangeetanadgir commented on jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
> +                List<String> mainWorkflowsIds = executor.getMainWorkflowIdsByJobId(jobId, workflowType);
That jobid will be ignored during cancellation and in the api response it will mentioned as skipped.

2023-08-17 16:18 UTC, pradeeppalat01 approved these changes

2023-08-17 16:18 UTC, merged